### ISSUE TITLE
Runtime crash on iOS 8

### ISSUE THREAD

**Issue by jjshammas** [jordanbyron/react-native-quick-actions#12]
If I try to run an app on iOS 8 that uses this plugin, I crash immediately with this error:

```
dyld: Symbol not found: _OBJC_CLASS_$_UIApplicationShortcutIcon
```

**Comment by jordanbyron** [comment]
@Kemcake can you confirm this? TBH I didn't test iOS versions < 9

**Comment by ptmt** [comment]
+1. I'm actually even can't compile with XCode 6. Yeah, this is my fault as a developer to forget about this when deploying to AppStore.

**Comment by jordanbyron** [comment]
@ptmt @jjshammas since I assume you both have the iOS 8.x simulator installed, can you try changing the line in your `AppDelegate.m` file to this:

```objective-c
- (void)application:(UIApplication *)application performActionForShortcutItem:(NSObject *)shortcutItem completionHandler:(void (^)(BOOL succeeded)) completionHandler {
  [RNQuickActionManager onQuickActionPress:shortcutItem completionHandler:completionHandler];
}
```

I'm curious to see if that works.

**Comment by jordanbyron** [comment]
@jjshammas @ptmt at this point I'm pretty close to saying, "It just ain't gonna work", but I'm willing to be proven wrong. I spent a little while playing around with the 8.x iOS simulator and I can't get it working without removing nearly all references to `UIApplicationShortcut` classes.

@Kemcake let us know if there is something magic you did you get it working that we aren't doing.

**Comment by grabbou** [comment]
Can't we use compile-time macros? http://stackoverflow.com/a/19790136

More details on various techniques here https://developer.apple.com/library/ios/documentation/DeveloperTools/Conceptual/cross_development/Introduction/Introduction.html

**Comment by ptmt** [comment]
It would be nice solution if Apple can recompile apps against each SDK. As far as I understand, they don't do it, so we need a dynamic runtime checking. I'm thinking about something like this: 
```
@interface RCTApplicationShortcutItem : NSObject
@end

@implementation RCTApplicationShortcutItem

- (instancetype)init
{
    Class UIApplicationShortcutItem = NSClassFromString(@"UIApplicationShortcutItem");
    if (NSClassFromString(@"UIApplicationShortcutItem")) {
        return [[UIApplicationShortcutItem alloc] init];;
    }
    return self;
}

@end
```

I hope to find the better and shorter solution, if not, will try to use this approach and test it today.

Too bad that there is at 17% share by iOS8, and it's even more on our target audience.

**Comment by ptmt** [comment]
So, I wasted a few hours on #13, but it's scary me. I would go with Weak Linking (with simple Class checking as you already have in master) or even just would set target = iOS9 (sorry iOS 8 users).

**Comment by jordanbyron** [comment]
Since we don't have any sane solutions for this issue I am going to say we just don't support older versions of iOS for the time being. If anyone wants to work on this more I'd be happy to review their work and merge it in if it doesn't add a ton of complexity. :8ball:
