### ISSUE TITLE
postinstall script is failing on Windows

### ISSUE THREAD

**Issue by sevachb** [jordanbyron/react-native-quick-actions#15]
Npm installing react-native-quick-actions on Windows fails with:

npm ERR! react-native-quick-actions@0.1.2 postinstall: `scripts/postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-quick-actions@0.1.2 postinstall script 'scripts/postinstall'.
npm ERR! This is most likely a problem with the react-native-quick-actions package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-native-quick-actions
npm ERR! There is likely additional logging output above.

This looks very similar to https://github.com/use-init/init/issues/89. Removing the informational postinstall script or finding a way to construct the path to work cross-OS seem like the potential solutions.

**Comment by grabbou** [comment]
I am actually wondering if we need it at all. Seems pretty non-standard in the existing ecosystem @jordanbyron ?

**Comment by jordanbyron** [comment]
Agreed. I was trying to be helpful because prior to rnpm and the updated
"Linking Libraries" docs this was a complicated and not very well
documented procedure. I'm pretty busy right now but if someone can send a
PR I'll merge it and publish a new release.

On Tue, Feb 16, 2016 at 1:27 PM Mike Grabowski <notifications@github.com>
wrote:

> I am actually wondering if we need it at all. Seems pretty non-standard in
> the existing ecosystem @jordanbyron <https://github.com/jordanbyron> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jordanbyron/react-native-quick-actions/issues/15#issuecomment-184813685>
> .
>
-- 
Jordan

**Comment by sevachb** [comment]
Agreed. I'll PR the change soon.

**Comment by jordanbyron** [comment]
#16 closes this issue
