### ISSUE TITLE
Implement `popInitialGesture`.

### ISSUE THREAD

**Issue by grabbou** [jordanbyron/react-native-quick-actions#4]
When app is cold-launched with gesture

Pull request submitted. Currently being tested.

BTW, I think we could've aligned even more with the PushNotificationsIOS api and provide full flow support and `addListener` without calling DeviceEventEmitter.

**Comment by jordanbyron** [comment]
https://github.com/jordanbyron/react-native-quick-actions/releases/tag/0.0.3

**Comment by jordanbyron** [comment]
@grabbou created issue #6 as well
