### ISSUE TITLE
[Android] Android doesn't save UserInfo in intent

### ISSUE THREAD

**Issue by ItsNoHax** [jordanbyron/react-native-quick-actions#51]
There is inconsistent behaviour between iOS and Android.
You are only saving the type of shortcut in Android's intent while iOS also saves the UserInfo so that it is available even after the app is killed.

Edit: Because we need the information to persist after the app gets killed I made my own branch with a somewhat ugly but functional change. https://github.com/ItsNoHax/react-native-quick-actions/commit/ffee10b8496b3ede28f04bdb954b9b9d9588f00b

I'd rather see this get implemented in this library so that I don't have to maintain a fork. If you give me a good indication of how I should implement this, I will gladly make you a proper pull request.

**Comment by jordanbyron** [comment]
Hey @ItsNoHax!

I noticed that as well when this was originally implemented, but I assumed it was a limitation of Androids shortcut functionality. Can you submit this as a PR so we can discuss the code there?

Thanks!

Jordan

**Comment by ItsNoHax** [comment]
Say no more.

Let me clean up the commit history and look into serializing the whole user info  JSON object instead of only the url.

Alberto
