### ISSUE TITLE
npm repo not update yet

### ISSUE THREAD

**Issue by lucky-xiaohu** [jordanbyron/react-native-quick-actions#61]
I have install this module with `npm install react-native-quick-actions --save`, the version i get still 0.3.6, it is about 8 month ago, new merge since then has not update to npm repo yet.
so it is time to update to npm repo or i have to install newest version from github?

**Comment by jordanbyron** [comment]
@lucky-xiaohu the only significant code changes that haven't been released is switching to use the main thread in iOS. Aside from that all of the recent changes have been to documentation, so `0.3.6` should be good to go.
