### ISSUE TITLE
Unable to resolve path to module

### ISSUE THREAD

**Issue by Dexwell** [jordanbyron/react-native-quick-actions#65]
Hey, thank you for this awesome library! 💖

It works great, however my ESLint is complaining:

> Unable to resolve path to module 'react-native-quick-actions'.

Despite installation through npm. Other packages don't have this issue.
Could you look into this?

**Comment by jordanbyron** [comment]
Hey Dexwell. Sounds like you've got a configuration problem with ESLint and/or your package setup. You're better off posting this to Stackoverflow or an equivalent site. This tracker is for bug reports and feature requests for `react-native-quick-actions`. I doubt ESLint expects package maintainers to do anything special to support their linter, but if you find there is something this library should be doing feel free to open a PR and I'll gladly review it.

**Comment by Dexwell** [comment]
I think I figured out what caused it. Your package has separate `index.ios.js` and `index.android.js` files. Most other packages have one `index.js` file that includes the appropriate files based on the platform. This is probably what ESLint was looking for.

Anyway, adding this to my ESLint fixed it for me.

````json
"settings": {
  "import/resolver": {
    "node": {
      "extensions": [
        ".js",
        ".android.js",
        ".ios.js"
      ]
    }
  }
}
````
