### ISSUE TITLE
android:launchMode="singleTop" not receiving quickActionShortcut events

### ISSUE THREAD

**Issue by JonasWho** [jordanbyron/react-native-quick-actions#66]
As the docs state, it should be only `android:launchMode="standard"` that does not receive `quickActionShortcut` events from `DeviceEventEmitter` but I'm using `singleTop` and experiencing the same behaviour.
Actually, it seems to be the case on Android no matter what launchmode I choose.

Anybody else experiencing this? 

React Native 0.54.4
Device: Samsung Galaxy S8
OS: Android 8.0.0

**Comment by ItsNoHax** [comment]
I sent a PR to fix this MONTHS ago: https://github.com/jordanbyron/react-native-quick-actions/pull/54

But here we are...

**Comment by JonasWho** [comment]
@ItsNoHax thanks, maybe I'll jump on over to your fork then, or have you changed other stuff dramatically?

**Comment by jordanbyron** [comment]
@JonasWho if you take a peek at #54 you can get the backstory, but the tl;dr is I was not able to manually QA test the Android PR and haven't had anyone step up to help out. The android code in this repo was written by someone else which means I'm not super comfortable with it, and making changes to it. That combined with a lack of automated tests and my unfamiliarity using RN on Android, here we are.

**Comment by JonasWho** [comment]
@jordanbyron ok, that's fair. I would love to help, but also do not have the capabilities unfortunately :(
