### ISSUE TITLE
open specific screen using 3d touch react-native-quick-action

### ISSUE THREAD

**Issue by aminvb12** [jordanbyron/react-native-quick-actions#75]
Hey guys
I'm using react-navigation and also define some screen.
I set up deep linking but I can't navigate to specific screen with react-native-quick-action.
react-native-quick-action work well but it just open up first screen.
How can I navigate to specific screen using react-native-quick-action?

**Comment by jordanbyron** [comment]
Hi @aminvb12,

This seems more like a question better suited for StackOverflow rather than our bug tracker. If you think there is a defect in react-native-quick-actions or a feature that could be added to allow for the type of workflow you are suggesting then this is the right place. Best of luck!

**Comment by ShuKTan** [comment]
@aminvb12  did you find the solution for this? I am having same problem in my app.
