### ISSUE TITLE
[Naming] Shouldn't it be popInitialAction

### ISSUE THREAD

**Issue by grabbou** [jordanbyron/react-native-quick-actions#8]
Just wondering, I think it fits better than `gesture` :+1:

**Comment by jordanbyron** [comment]
:+1: We'll probably also want to reach into the Obj-C code and rename references to `initialGesture` as well.

**Comment by grabbou** [comment]
Oh yeah, initialAction :) Will submit PR and this time my commits are going to land in master log!

**Comment by jordanbyron** [comment]
Closed by #9
