### ISSUE TITLE
Question : how use navigation on popInitialAction Promise ?

### ISSUE THREAD

**Issue by stephane-r** [jordanbyron/react-native-quick-actions#83]
Hi Jordan !

I try your very nice module on react-native app, All work perfectly :)

But, i've a question : `QuickActions.popInitialAction` is not executed in a react component, so, how i can use for example Navigation props ?

I've try to use [this method](https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html), but i think it's not the best solution :D 

Thank you Jordan

**Comment by jordanbyron** [comment]
Hey @stephane-r,

I'm glad to hear you are enjoying this library. For questions like this your best off posting to a place like StackOverflow. This is our libraries bug and feature tracker. My guess is it's a timing problem, but with more context I'm sure someone in a troubleshooting community would be able to get you up and running.

Best of luck -- Jordan
