### ISSUE TITLE
[Question] Android Minimum SDK

### ISSUE THREAD

**Issue by kevinhermawan** [jordanbyron/react-native-quick-actions#86]
Hi @jordanbyron, can you explain why this library need Android SDK min 21? I've been tested on Android devices with SDK 19 and decreasing min SDK on this library to 19 and still work.

**Comment by jordanbyron** [comment]
I don’t recall exactly why. A git blame in the right place would answer that question. 

Jordan

**Comment by kevinhermawan** [comment]
Thanks, answered by this PR #74
