### ISSUE TITLE
QuickActions has a Incorrect display

### ISSUE THREAD

**Issue by pssgo** [jordanbyron/react-native-quick-actions#89]
![image](https://user-images.githubusercontent.com/16378134/63140190-a6fcae80-c013-11e9-8fe7-c02860ff9c2f.png)

![image](https://user-images.githubusercontent.com/16378134/63140201-b845bb00-c013-11e9-885c-4ed92b84f412.png)

![image](https://user-images.githubusercontent.com/16378134/63140221-c98ec780-c013-11e9-88d1-1e5b6cbc07c5.png)

When I removed the dependency package, it worked fine, and the quick menu did not display correctly, The quickActionShortcut event will not be triggered

![image](https://user-images.githubusercontent.com/16378134/63140236-d90e1080-c013-11e9-93fe-d005ad77eec2.png)

![image](https://user-images.githubusercontent.com/16378134/63140173-8d5b6700-c013-11e9-9df3-20f1a1cebf2b.png)

```
    "react-native-quick-actions": "^0.3.12",
    "react": "16.8.6",
    "react-native": "0.60.4",
```

is this a bug ?

**Comment by jordanbyron** [comment]
@pssgo review the README again. It appears you added the package in the wrong place. `new AppShortcutsPackage()` should be added to 

```java
// MainApplication.java

public List<ReactPackage> createAdditionalReactPackages() {
  return Arrays.<ReactPackage>asList(
    new AppShortcutsPackage()
  );
}
```
